language: python
os:
- linux
python:
- '3.6'
install:
#- pip install ml_ms4alg
#- pip install tqdm click Cython klusta klustakwik2
#- pip install spyking-circus
- pip install .
- pip install pytest
- pip install mountainlab_pytools kbucket
script: pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: Uq9cB1OWvw59aXrWBia4+OBBpJDl3/U21V/CtdYxkNVFUVP1oCdx2OyJa9LVibnQNTxZ2aGS8oZKtf74P3LEqbqryMYMLZdko65hxaJmPVlR0+ytVZTGEFVPIzXjzmCqMAw93jmZ374h5Hmj5yylzJfm/VqfT1nTOCgxiRl16MyYuV/LMHSLIv5GqbdhMUGCdLlPQJ8WQTwrognW1EIQJRqJKuyDtxWVsxOo9Yh8qjgvxn0hh8VA4CrY3IdDpTUerQ/j5VSyU8UHmb3MiEpfXGya+NrqtVRb5ypVpf/xF5tprgbm9xr5KJOcdj6LR6SmesoHEb4NAKuvXRrhE4+IH2SEyVjUEupfqISIWqZHRmoQA+0rpeNcWKPX9/DJYr2jmt54ZW1XGdc5o31fABzFyJkLrf8aJ6kyJZWcGl6LDlJ+AGODZvt1XfTsO3KlFnzTtxypVbh2fppK1UtYVY8NA3MLFb1lyXIZ+hztzK9XHKSBHHYq4NmCC0zTAueFQfolVNDALdzWONOP14p2CvXOJ8OG52AgHLClFpidmY6TtbvfousGu4BF3CjVfpsIv7vNmHjCnzu7UGHwsHlXLbFKp6ipgg/cqYbzdcNQNJboiOq03xuY8Qvp07h57Zw4/7/PWJ8/SAWmwxZAC+y4l7Dat2MTYxGIEahK5Ts4f9hG4gU=
